# Generated by Django 3.2.4 on 2021-06-11 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 14, 6, 25, 185966)),
        ),
    ]
