# Generated by Django 3.2.4 on 2021-06-11 14:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MB', '0002_alter_mensajes_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 14, 28, 23, 62973)),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MB.perfil'),
        ),
    ]
