# Generated by Django 3.2.4 on 2021-06-11 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MB', '0003_auto_20210611_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 14, 28, 55, 170159)),
        ),
    ]
